### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by iamshyamganatra**
updated the topic name to publish velocity command from CLI.

### CODE REVIEW

**Comment by chapulina** [comment]
The topic should be correct because it's [being remapped](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/150142016b2f7ee872b90ff53cc5ed8c6803d974/gazebo_plugins/worlds/gazebo_ros_diff_drive_demo.world#L226)

Is that not working for you?

**Comment by iamshyamganatra** [comment]
Apparently no, 
but I'm using Dashing & I think the remapping is done only in eloquent demos.
image

**Comment by chapulina** [comment]
Interesting, dashing is also supposed to be [remapping](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/dashing/gazebo_plugins/worlds/gazebo_ros_diff_drive_demo.world#L226). I see on your screenshot that you're using `eloquent` though. Mixing them is a problem right now, see https://github.com/ros-simulation/gazebo_ros_pkgs/issues/991#issuecomment-546661756

**Comment by iamshyamganatra** [comment]
oh sorry, I messed up there, I had sourced `Dashing` and pasted the command from tutorial.2

**Pull request closed without merging**
